#ifndef SACTOR_CONFIG_H
#define SACTOR_CONFIG_H

//
// Actor mailbox message queue configs
//
#ifndef SACTOR_ACTOR_MAILBOX_QUEUE_RECEIVE_TIMEOUT_IN_MS
#define SACTOR_ACTOR_MAILBOX_QUEUE_RECEIVE_TIMEOUT_IN_MS (1000)
#endif

//
// Delay message service configs
//
#ifndef SACTOR_DELAY_MESSAGE_SERVICE_MAX_ITEM_COUNT
#define SACTOR_DELAY_MESSAGE_SERVICE_MAX_ITEM_COUNT (64)
#endif

#ifndef SACTOR_DELAY_MESSAGE_SERVICE_LOCK_WAIT_TIME_IN_MS
#define SACTOR_DELAY_MESSAGE_SERVICE_LOCK_WAIT_TIME_IN_MS (100)
#endif

#endif
